name: "Test ikisocket"

on:
  push:
    branches:
      - master
      - main
    paths:
      - "ikisocket/**"
  pull_request:
    paths:
      - "ikisocket/**"

jobs:
  Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - 1.20.x
          - 1.21.x
          - 1.22.x
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "${{ matrix.go-version }}"
      - name: Run Test
        working-directory: ./ikisocket
        run: go test -v -race ./...
